trigger:
- master
- dev/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  PTM.Version: 1.6
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom-jacocomerge.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'verify'
 
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'jaCoCo' 
    summaryFileLocation: 'target/codecoverage/jacoco.xml'
    reportDirectory: 'target/codecoverage'
    
- script: |
    docker build -t lgblaumeiser/ptm_backend:$(PTM.Version)_$(Build.BuildNumber) .
    docker login -u lgblaumeiser -p $(Docker.Passwd) https://hub.docker.com/
    docker push lgblaumeiser/ptm_backend:$(PTM.Version)_$(Build.BuildNumber)
    