trigger:
- master
- dev/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom-jacocomerge.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'verify'
 
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'jaCoCo' 
    summaryFileLocation: 'target/codecoverage/jacoco.xml'
    reportDirectory: 'target/codecoverage' 