trigger:
- master
- dev/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud' 
  inputs: 
    SonarCloud: 'https://sonarcloud.io/' 
    organization: ProjectTimeManager 
    projectKey: 84ac5cdf91f59bcbf1b7210c87074aec52c86ec5
    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    sonarQubeRunAnalysis: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom-jacocomerge.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'verify'
 
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'jaCoCo' 
    summaryFileLocation: 'target/codecoverage/jacoco.xml'
    reportDirectory: 'target/codecoverage' 
